"""Add dna_analysis table

Revision ID: bc3196bfea5c
Revises: 9e0f97e315d0
Create Date: 2025-08-04 01:55:25.633593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc3196bfea5c'
down_revision: Union[str, None] = '9e0f97e315d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dna_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_content', sa.Text(), nullable=True),
    sa.Column('analysis_result', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dna_analysis_id'), 'dna_analysis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dna_analysis_id'), table_name='dna_analysis')
    op.drop_table('dna_analysis')
    # ### end Alembic commands ###
