version: '3.9'

services:
  backend:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: healthy_diet_backend
    env_file:
      - ../backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ..:/workspaces/health-diet-finder

  db:
    image: postgres:15
    container_name: healthy_diet_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: healthy_diet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
